### ISSUE TITLE
Indication of how many letters are being used should be somewhere without having to press space to see

### ISSUE THREAD

**Issue by Tree52** [Angyeoung/Amok-Toolbox#5]

**Comment by Angyeoung** [comment]
Now displays "XXXX" or "XX" based on settings
![image](https://user-images.githubusercontent.com/73502881/210477565-d5b702da-81c1-44b8-9bb4-86c97cb91cdc.png)
![image](https://user-images.githubusercontent.com/73502881/210477596-308d7c16-b8f7-4ffa-bfa3-02ca96bf0cd8.png)
